/**
 * Control-plane helpers for getting the shim daemon into a sandbox and running.
 *
 * The shim (`@racecar/shim`) is a separate package the sandbox snapshot does not
 * carry — the snapshot is the user's project image. So at sandbox boot the
 * control plane *delivers* the shim as a single self-contained bundle (one
 * `base64 -d` into a file, the same file-shipping pattern the run wrapper uses)
 * and *launches* it detached in its own tmux session. A long-lived server must
 * never be a child of a synchronous exec — that hangs the exec until it exits —
 * so, exactly like the agent run, it goes into tmux via `new-session -d`.
 *
 * This module owns only the shell-script generation and the token contract, so
 * the strings stay testable and the wire names (env var, port, session) have one
 * source of truth. The token value itself is generated by {@link generateShimToken}
 * and injected as an env var at sandbox creation, never interpolated into a
 * command line here.
 */
import { randomBytes } from 'node:crypto';

/**
 * Env var carrying the per-sandbox shim token. Must match `@racecar/shim`'s
 * `SHIM_TOKEN_ENV`; duplicated here so `@racecar/core` need not depend on the
 * shim package (which would drag its WebSocket server into the control plane).
 */
export const SHIM_TOKEN_ENV = 'RACECAR_SHIM_TOKEN';

/** Env var overriding the shim's listen port. Matches shim `SHIM_PORT_ENV`. */
export const SHIM_PORT_ENV = 'RACECAR_SHIM_PORT';

/** Default shim port. Matches shim `SHIM_DEFAULT_PORT`. */
export const SHIM_DEFAULT_PORT = 3100;

/** The detached tmux session the shim runs in. Matches shim `SHIM_TMUX_SESSION`. */
export const SHIM_TMUX_SESSION = 'racecar-shim';

/** Absolute path the shim bundle is written to and run from inside the sandbox. */
export const SHIM_BUNDLE_PATH = '/opt/racecar/racecar-shim.cjs';

/**
 * In-sandbox path of the token file the daemon reads. Must match the shim's
 * {@link shimTokenFilePath}(`$HOME`); duplicated here (like {@link SHIM_TOKEN_ENV})
 * so `@racecar/core` need not depend on `@racecar/shim`. The `$HOME` is expanded
 * by the sandbox shell, so the literal path is resolved there, not on the host.
 */
export const SHIM_TOKEN_FILE = '"$HOME"/.racecar/shim.token';

/** A cryptographically strong, URL-safe per-sandbox token (base64url, 32 bytes). */
export function generateShimToken(bytes = 32): string {
  return randomBytes(bytes).toString('base64url');
}

/** Single-quote a value for safe interpolation into a POSIX shell command. */
function sq(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/** Base64 a UTF-8 string for transport into a `base64 -d` in the sandbox. */
function b64(value: string): string {
  return Buffer.from(value, 'utf8').toString('base64');
}

/** Options for {@link shimBootScript}. */
export interface ShimBootParams {
  /** The bundled daemon source (contents of `dist/racecar-shim.cjs`). */
  readonly bundle: string;
  /** Where to write and run the bundle. Defaults to {@link SHIM_BUNDLE_PATH}. */
  readonly bundlePath?: string;
  /** tmux session to run in. Defaults to {@link SHIM_TMUX_SESSION}. */
  readonly session?: string;
}

/**
 * Script that writes the shim bundle to disk and (re)launches it detached in its
 * own tmux session. Idempotent: it kills any prior shim session first, so a
 * re-run after a sandbox restart replaces a stale daemon rather than failing.
 *
 * The token and port are read from the daemon's environment (injected at sandbox
 * creation), not passed here — so no secret ever enters this command string. The
 * daemon logs newline-delimited JSON to `~/.racecar/shim.log`.
 */
export function shimBootScript(params: ShimBootParams): string {
  const path = params.bundlePath ?? SHIM_BUNDLE_PATH;
  const session = params.session ?? SHIM_TMUX_SESSION;
  const dir = path.slice(0, path.lastIndexOf('/')) || '/';
  return [
    'set -eu',
    `mkdir -p ${sq(dir)} "$HOME/.racecar"`,
    `printf '%s' ${sq(b64(params.bundle))} | base64 -d > ${sq(path)}`,
    ...writeTokenFileLines(),
    ...relaunchLines(path, session),
  ].join('\n');
}

/**
 * Lines that materialize the token file `0600` from {@link SHIM_TOKEN_ENV}. They
 * reference the env var *name* only, so no token literal enters the command
 * string (and thus no exec log). At creation the value comes from the sandbox's
 * baked-in env var; at rotation it comes from the token passed out-of-band to the
 * exec that runs {@link shimRebootScript}, so the same lines write the new token.
 */
function writeTokenFileLines(): string[] {
  return [
    'umask 077',
    `printf '%s' "$${SHIM_TOKEN_ENV}" > ${SHIM_TOKEN_FILE}`,
    `chmod 600 ${SHIM_TOKEN_FILE}`,
  ];
}

/** Lines that (re)start the shim daemon detached in its own tmux session. */
function relaunchLines(path: string, session: string): string[] {
  const launch = `node ${sq(path)} > "$HOME/.racecar/shim.log" 2>&1`;
  return [
    `tmux kill-session -t ${sq(session)} 2>/dev/null || true`,
    `tmux new-session -d -s ${sq(session)} ${sq(launch)}`,
  ];
}

/** Options for {@link shimRebootScript}. */
export interface ShimRebootParams {
  /** Where the bundle already lives. Defaults to {@link SHIM_BUNDLE_PATH}. */
  readonly bundlePath?: string;
  /** tmux session to run in. Defaults to {@link SHIM_TMUX_SESSION}. */
  readonly session?: string;
}

/**
 * Script that rotates the per-sandbox shim token and restarts the daemon without
 * re-delivering the bundle (which is already on disk). It rewrites the token file
 * from {@link SHIM_TOKEN_ENV} — supplied out-of-band as the exec's env, so the
 * new token never appears in the command — then kills and relaunches the daemon's
 * tmux session so it reads the rotated token. Any client using the old token is
 * disconnected and must reconnect with the new one.
 */
export function shimRebootScript(params: ShimRebootParams = {}): string {
  const path = params.bundlePath ?? SHIM_BUNDLE_PATH;
  const session = params.session ?? SHIM_TMUX_SESSION;
  return [
    'set -eu',
    'mkdir -p "$HOME/.racecar"',
    ...writeTokenFileLines(),
    ...relaunchLines(path, session),
  ].join('\n');
}

/**
 * Script that reports whether the shim's tmux session is alive and prints the
 * tail of its log. Used to verify the daemon came up after {@link shimBootScript}.
 */
export function shimStatusScript(session: string = SHIM_TMUX_SESSION): string {
  return [
    `if tmux has-session -t ${sq(session)} 2>/dev/null; then printf 'RUNNING\\n'; else printf 'STOPPED\\n'; fi`,
    `tail -n 20 "$HOME/.racecar/shim.log" 2>/dev/null || true`,
  ].join('\n');
}

/**
 * Script that prints the sandbox's per-sandbox shim token to stdout. The token is
 * injected as an env var at creation and deliberately never persisted to a label
 * or local disk, so a client that wants to reach the shim (`racecar chat`,
 * `racecar run`) reads it back from the running sandbox over the exec channel —
 * keeping the token a property the control plane owns without a second copy on the
 * host. The caller must capture this output without echoing it (it is redacted
 * from any printed output regardless).
 */
export function shimTokenScript(): string {
  return `printf '%s' "${'$'}${SHIM_TOKEN_ENV}"`;
}
